CREATE TABLE IF NOT EXISTS house (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  house_title VARCHAR(100) NOT NULL,
  house_address VARCHAR(255) NOT NULL,
  house_area DECIMAL(10,2) NOT NULL DEFAULT 0,
  house_price DECIMAL(10,2) NOT NULL DEFAULT 0,
  house_type VARCHAR(50) DEFAULT NULL,
  house_floor VARCHAR(20) DEFAULT NULL,
  house_direction VARCHAR(20) DEFAULT NULL,
  house_status ENUM('vacant', 'rented') NOT NULL DEFAULT 'vacant',
  house_desc TEXT,
  house_image VARCHAR(255) DEFAULT NULL,
  owner_id BIGINT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
