CREATE TABLE IF NOT EXISTS rental_application (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  house_id BIGINT NOT NULL,
  apply_reason VARCHAR(500) DEFAULT NULL,
  lease_start_date DATE DEFAULT NULL,
  lease_end_date DATE DEFAULT NULL,
  rent_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  apply_status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  apply_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  review_time TIMESTAMP NULL DEFAULT NULL,
  reviewer_id BIGINT DEFAULT NULL,
  reject_reason VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
